version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command:
      - start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./build/libs:/opt/keycloak/providers
